### ISSUE TITLE
Error when hit python server.py -d

### ISSUE THREAD

**Issue by brijeshtechximum** [lnxg33k/email-header-analyzer#14]
E:\email-header-analyzer-master\email-header-analyzer-master\MHA>python server.py -d
Traceback (most recent call last):
  File "server.py", line 5, in <module>
    from email.Parser import HeaderParser
ModuleNotFoundError: No module named 'email.Parser'

**Comment by hugofloss** [comment]
Just change:

`from email.Parser import HeaderParser`

to

`from email.parser import HeaderParser`

and you'll be fine
